project/urls.py
from django.urls import path
from . import views

app_name = "project"

urlpatterns = [
    path("", views.index, name="index"),
    path("main/", views.main, name="main"),
    path("new_event", views.new_event, name="new_event"),
    path("listevents/", views.listevents, name="listevents"),
    path("blog/", views.blog, name="blog"),
    path("newblog/", views.newblog, name="newblog"),
    path("delete/", views.delete, name="delete"),
    path("editevent/<int:event_id>/", views.editevent, name="editevent"),
    path("deleteevent/<int:event_id>/", views.deleteevent, name="deleteevent"),
]

scheduler/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("", include("project.urls")),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = "users"
urlpatterns = [
    # Default auth urls
    path("", include("django.contrib.auth.urls")),
    path("register/", views.register, name="register"),
]

project/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Event(models.Model):
    description = models.CharField(max_length=150)
    start_time = models.DecimalField(max_digits=4, decimal_places=2)
    end_time = models.DecimalField(max_digits=4, decimal_places=2)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.description


class Blog(models.Model):
    topic = models.CharField(max_length=150)
    content = models.TextField()

    def __str__(self):
        return self.topic

users/models.py
from django.db import models

# Create your models here.

project/forms.py
from django import forms
from .models import Event, Blog


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ["description", "start_time", "end_time"]
        labels = {"description": "", "start_time": "", "end_time": ""}


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ["topic", "content"]
        labels = {"topic": "", "content": ""}

project/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .models import Event, Blog
from .forms import EventForm, BlogForm


def index(request):
    return render(request, "project/index.html")


@login_required
def listevents(request):
    events = Event.objects.filter(owner=request.user).all()
    # Just an extra layer of protection for some clever hackers ;)
    for event in events:
        if event.owner != request.user:
            raise Http404
    context = {"events": events}
    return render(request, "project/listevents.html", context)


@login_required
def main(request):
    maximized_event = []
    events = list(Event.objects.filter(owner=request.user).order_by("end_time"))
    invalid_events = []
    for event in events:
        if (
            event.start_time > 24
            or event.end_time > 24
            or event.end_time < 0
            or event.start_time < 0
        ):
            events.remove(event)
            invalid_events.append(event)
    if len(events) == 0:
        context = {"events": maximized_event, "invalid_events": invalid_events}
        return render(request, "project/main.html", context)
    else:
        k = 0
        maximized_event.append(events[k])
        for i in range(1, len(events)):
            st = events[i].start_time
            if st >= events[k].end_time:
                maximized_event.append(events[i])
                k = i
        context = {"events": maximized_event, "invalid_events": invalid_events}
        return render(request, "project/main.html", context)


@login_required
def new_event(request):
    """Add a new event"""
    if request.method != "POST":
        # The case where no data is submitted
        form = EventForm()  # Spawn an empty instance
    else:
        # The case where POST data is submitted
        form = EventForm(data=request.POST)
        if form.is_valid():
            new_event = form.save(commit=False)
            new_event.owner = request.user
            new_event.save()
            return redirect("project:listevents")
    context = {"form": form}
    return render(request, "project/new_event.html", context)


def blog(request):
    """A shared blog site for students to share their learning progress"""
    blogs = Blog.objects.order_by("topic")
    context = {"blogs": blogs}
    return render(request, "project/blogs.html", context)


@login_required
def newblog(request):
    """Page to add new blogs"""
    if request.method != "POST":
        # The case where no data is submitted
        form = BlogForm()  # Spawn an empty instance
    else:
        # The case where POST data is submitted
        form = BlogForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("project:blog")
    context = {"form": form}
    return render(request, "project/newblog.html", context)


def delete(request):
    Event.objects.filter(owner=request.user).delete()
    return redirect("project:listevents")


def editevent(request, event_id):
    event = Event.objects.get(id=event_id)
    if request.method != "POST":
        form = EventForm(instance=event)
    else:
        form = EventForm(instance=event, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("project:listevents")

    context = {"event": event, "form": form}
    return render(request, "project/editevent.html", context)


def deleteevent(request, event_id):
    Event.objects.filter(owner=request.user).filter(id=event_id).delete()
    return redirect("project:listevents")

users/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login

# Thank god for django methods


def register(request):
    # POST and GET are the two main possible methods
    # If the user is not posting data...
    if request.method != "POST":
        # Create a user
        form = UserCreationForm()
    else:
        # Now we are posting... the data would be the form
        # We need to process the form
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # Log that user in with their new account
            login(request, new_user)
            return redirect("project:index")

    context = {"form": form}
    return render(request, "registration/register.html", context)

project/templates/project/blogs.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'project/style.css' %}"
    />
    <title>Student Posts</title>
  </head>
  <body>
    <div class="menu">
      <div class="blog-menu">
        <a href="{% url 'project:index' %}"> Home page</a>
      </div>
      <div class="blog-menu">
        <a href="{% url 'project:newblog' %}"> Add a new blog post!</a>
      </div>
    </div>

    <div class="heading"><h2>Welcome to Student Blog Posts</h2></div>
    <p>&nbsp;</p>
    <div class="description">
      Welcome to Student Blog Posts
      <center>
        <p>
          This page is created to allow students to have a place to share their
          learning experience to all the users oline, whether they are a
          registered user or not. Using this feature, users of this site can
          read other people's posts as well as login to create new posts. Enjoy!
        </p>
      </center>
    </div>
    <center>
      {%for blog in blogs%}
      <div>
        <p><b>{{blog.topic}}</b></p>
        <p>{{blog.content}}</p>
        <p>&nbsp</p>
      </div>
      {%endfor%}
    </center>
  </body>
</html>

project/templates/project/editevent.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'project/style.css' %}"
    />
    <title>Document</title>
  </head>
  <body>
    <div class="container">
      <div class="menu">
        <div class="menu-link">
          {%if user.is_authenticated %} Hello, {{user.username}}.
          <a href="{% url 'users:logout' %}"> Log out</a> {%else%}
          <a><a href="{% url 'users:register' %}">Register</a> --OR--</a>
          <a href="{% url 'users:login' %}">Login</a> {%endif%}
        </div>

        <div class="menu-link">
          <a href="{% url 'project:listevents' %}"> view events </a>
        </div>

        <div class="menu-link">
          <a href="{% url 'project:main' %}"> arranged schedule </a>
        </div>

        <div class="menu-link">
          <a href="{% url 'project:new_event' %}">
            Click here to add a new event
          </a>
        </div>
      </div>
    </div>

    <p>Edit:</p>
    <form action="{%url 'project:editevent' event.id%}" method="post">
      {%csrf_token%} {{form.as_p}}
      <button name="submit">Save Changes</button>
    </form>
  </body>
</html>

project/templates/project/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'project/style.css' %}"
    />
    <title>Document</title>
  </head>
  <body>
    <div class="container">
      <div class="menu">
        <div class="menu-link">
          {%if user.is_authenticated %} Hello, {{user.username}}.
          <a href="{% url 'users:logout' %}"> Log out</a> {%else%}
          <a><a href="{% url 'users:register' %}">Register</a> --OR--</a>
          <a href="{% url 'users:login' %}">Login</a> {%endif%}
        </div>

        <div class="menu-link">
          <a href="{% url 'project:listevents' %}">
            View Events
          </a>
        </div>

        <div class="menu-link">
          <a href="{% url 'project:main' %}">
            arranged schedule
          </a>
        </div>

        <div class="menu-link">
          <a href="{% url 'project:new_event' %}">
            add new event
          </a>
        </div>
      </div>
    </div>

    <div class="heading"><h2>Welcome to your scheduler</h2></div>
    <div class="cont">
    <div class="description">Scheduler is a tool that allows you to keep track of all your events using a clean and simple interface. 
      In the case where there you have many overlapping events you want to attend, Scheduler can help you sort out your options. 
      In a time like this where many classes are moving online, online learners can often feel isolated, so we also created a blog post 
      feature that allows people to share their online learning experience and connect with other online learners.</div>
    </div> 
      <p>

        <div class="menu-link" style="text-align: center">
        <a href="{% url 'project:blog' %}">
          See The Student Blog Page
        </a></div>
      </p>
  </body>
</html>

project/templates/project/listevents.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'project/style.css' %}"
    />
    <title>Document</title>
  </head>
  <body>
    <div class="container">
      <div class="menu">
        <div class="menu-link">
          {%if user.is_authenticated %} Hello, {{user.username}}.
          <a href="{% url 'users:logout' %}"> Log out</a> {%else%}
          <a><a href="{% url 'users:register' %}">Register</a> --OR--</a>
          <a href="{% url 'users:login' %}">Login</a> {%endif%}
        </div>

        <div class="menu-link">
          <a href="{% url 'project:listevents' %}"> view events </a>
        </div>

        <div class="menu-link">
          <a href="{% url 'project:main' %}"> arranged schedule </a>
        </div>

        <div class="menu-link">
          <a href="{% url 'project:new_event' %}"> add new event </a>
        </div>
      </div>
    </div>
    <div class="heading">
      <h2>Welcome to your scheduler</h2>
    </div>

    <div class="description">
      <p><b>Events</b></p>
      {%for event in events%}
      <li>
        <b style="color: dodgerblue">{{event}}:</b> {{event.start_time}} ----
        {{event.end_time}} ------
        <a href="{% url 'project:editevent' event.id %}">Edit</a> -----
        <a href="{% url 'project:deleteevent' event.id%}">delete this event</a>
      </li>
      {%empty%}
      <p>You haven't added any events yet</p>
      {%endfor%}
    </div>

    <div class="links">
      <p>
        <a href="{% url 'project:new_event' %}"> Add new event </a>
      </p>
      {%if events%}
      <p>
        <a href="{% url 'project:main' %}"> See Arranged Schedule </a>
      </p>
      <p>
        <a href="{% url 'project:delete' %}"> Delete <b>ALL</b> events </a>
      </p>
      {%endif%}
    </div>
    <div class="home">
      <p>&nbsp;</p>
      <a href="{% url 'project:index' %}"> Home </a>
    </div>
  </body>
</html>

project/templates/project/main.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'project/style.css' %}"
    />
    <title>Main File</title>
  </head>
  <body>
    <div class="container">
      <div class="menu">
        <div class="menu-link">
          {%if user.is_authenticated %} Hello, {{user.username}}.
          <a href="{% url 'users:logout' %}"> Log out</a> {%else%}
          <a><a href="{% url 'users:register' %}">Register</a> --OR--</a>
          <a href="{% url 'users:login' %}">Login</a> {%endif%}
        </div>

        <div class="menu-link">
          <a href="{% url 'project:listevents' %}"> view events </a>
        </div>

        <div class="menu-link">
          <a href="{% url 'project:main' %}"> arranged schedule </a>
        </div>

        <div class="menu-link">
          <a href="{% url 'project:new_event' %}"> add new event </a>
        </div>
      </div>
    </div>

    <div class="heading"><p><h2>Welcome to Your Scheduler</p></h2></div>
    <div class="description">
      <p>
        <b>Here's your arranged schedule, optimized to contain the most number of events you can attend!</b>
      </p>

      <ul>
        {%for event in events%}

          <p><b style="color: dodgerblue">{{event}} </b>: {{event.start_time}} ---
          {{event.end_time}}</p>
        {%empty%}
        <p>Nothing added yet!</p>
        {%endfor%}
      </ul>

      {%if invalid_events%}
      <p>The following events time are not valid inputs!</p>
      <ul>
        {%for invalid_event in invalid_events%}
        <li>
          <b>{{invalid_event}} </b>: {{invalid_event.start_time}} ---
          {{invalid_event.end_time}}
        </li>
      </ul>
      {%endfor%} {%endif%}
      <p>&nbsp;</p>
      <p>Want to make changes?</p>
    </div>
      <div class="home"><a href="{% url 'project:listevents' %}">View events!</div></a>
      
      <div class="home">
        <p>&nbsp;</p>
        <a href="{% url 'project:index' %}"> Home </a>
      </div>
    
  </body>
</html>

project/templates/project/new_event.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'project/style.css' %}"
    />
    <title>Document</title>
  </head>
  <body>
    <div class="container">
      <div class="menu">
        <div class="menu-link">
          {%if user.is_authenticated %} Hello, {{user.username}}.
          <a href="{% url 'users:logout' %}"> Log out</a> {%else%}
          <a><a href="{% url 'users:register' %}">Register</a> --OR--</a>
          <a href="{% url 'users:login' %}">Login</a> {%endif%}
        </div>

        <div class="menu-link">
          <a href="{% url 'project:listevents' %}">
            Click here to view events
          </a>
        </div>

        <div class="menu-link">
          <a href="{% url 'project:main' %}">
            Click here for your arranged schedule
          </a>
        </div>

        <div class="menu-link">
          <a href="{% url 'project:new_event' %}">
            Click here to add a new event
          </a>
        </div>
      </div>
    </div>

    <p>Add a new event:</p>

    <form action="{%url 'project:new_event'%}" method="post">
      <! --- Attack safety insurance & render form as paragraph --->
      {%csrf_token%}
      <p>Name of the event {{form.description}}</p>
      <p>
        Starting time of the event (24h) (e.g 8.00, 20.00) {{form.start_time}}
      </p>
      <p>Ending time of the event (24h) (e.g 8.00, 20.00) {{form.end_time}}</p>
      <button name="submit">Add an Event</button>
    </form>
  </body>
</html>

project/templates/project/newblog.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <center>
      <p>Add a new blog post!</p>
      <form action="{% url 'project:newblog' %}" method="post">
        {%csrf_token%}
        <p>Enter the title of your post here: {{form.topic}}</p>
        <p>What would like to share?</p>
        <p>{{form.content}}</p>

        <button name="submit">Add Post</button>
      </form>
      <p>
        <a href="{% url 'project:blog' %}"
          ><b>Not sure what to write? Go back to posts</b></a
        >
      </p>
    </center>
  </body>
</html>